services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: greaticker
      MYSQL_USER: sseung00921
      MYSQL_PASSWORD: 1234
    volumes:
      - /Users/sangseung/Documents/mysql_data:/var/lib/mysql
      #- /Volumes/externalssd/DevRoot/Documents/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always


