spring:
  application:
    name: demo
  datasource:
    url: ${{ secrets.DATASOURCE_URL }}
    username: ${{ secrets.DATASOURCE_USERNAME }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: embedded

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate

  redis:
    host: redis
    port: 6379

#  kafka:
#    bootstrap-servers: kafka:9092  # Kafka 서버 주소
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: myGroup
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    properties:
#      security:
#        protocol: PLAINTEXT

my:
  app:
    secret-key: ${{ secrets.MY_APP_SECRET_KEY }}