spring:
  datasource:
    url: jdbc:mysql://localhost:3306/greaticker?allowPublicKeyRetrieval=true&useSSL=false
    username: sseung00921
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver