name: CI/CD for compromise-for-t2.micro

on:
  push:
    branches:
      - compromise-for-t2.micro  # 해당 브랜치에 푸쉬될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Gradle 빌드 수행
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      # 3. Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t greaticker_backend:latest .

      # 4. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Docker 이미지 푸쉬
      - name: Push Docker Image
        run: docker push greaticker_backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 6. EC2에 SSH로 접속하여 Docker Compose 실행
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 호스트
          username: ${{ secrets.EC2_USER }}  # EC2 사용자
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # SSH 개인 키
          script: |
            cd ~  # EC2의 홈 폴더 경로
            docker-compose down
            docker-compose pull
            docker-compose up -d
